# Generated by Django 5.0.1 on 2024-01-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department_name',
        ),
    ]
