# Generated by Django 5.0.1 on 2024-01-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveRequest', '0003_rename_other_reaoson_leaverequest_other_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(choices=[('SICK', 'Sick'), ('VACATION', 'Vacation'), ('FAMILY', 'Family'), ('ACCIDENT', 'Accident'), ('NO_PERMISSION', 'No Permission'), ('OTHER_REASON', 'Other Reason')], default='NO_PERMISSION', max_length=255),
        ),
    ]
