# Generated by Django 5.0.1 on 2024-01-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveRequest', '0004_alter_leaverequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='NOT_CHECKED', max_length=255),
        ),
    ]
